### ISSUE TITLE
PDF not rendered correctly

### ISSUE THREAD

**Issue by sedrubal** [Cimbali/pympress#188] opened 2021-04-09 22:22 UTC
### Environment
- Operating system and version: Arch Linux with KDE Plasma 5.21.4
- Python version: Python 3.9.2

### Pympress
- version: 1.5.3-2
- Installation method: source, AUR (yay)

### Expected behaviour
Some PDF files are not rendered correctly when they are opened with `pympress`.

### Steps to reproduce

Use this PDF file (rendered with matplotlib): [`execution-times.pdf`](https://github.com/Cimbali/pympress/files/6288744/execution-times.pdf)

```bash
$ pympress --log=DEBUG ./execution-times.pdf
```

### Problem
All labels are missing. It looks like this:

![Screenshot_20210410_001741](https://user-images.githubusercontent.com/5571650/114246169-38135c80-9992-11eb-9044-0c70fc287361.png)

Instead of this:

![image](https://user-images.githubusercontent.com/5571650/114246195-4eb9b380-9992-11eb-8d4d-2be71db80ce9.png)

What is reported in pympress.log?

Nothing that is realted to this problem:

```python
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pympress/util.py", line 81, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/usr/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
ERROR:pympress.extras:Video support using GStreamer is disabled.
INFO:pympress.extras:Caused by ValueError: Namespace GstPlayer not available
INFO:pympress.__main__:Pympress: 1.5.3 ; Python: 3.9.2 ; OS: Linux 5.10.28-1-lts #1 SMP Wed, 07 Apr 2021 15:18:42 +0000 ; Gtk 3.24.28 ; GLib 2.68.0 ; Poppler 21.04.0 cairo ; Cairo 1.17.4 , pycairo 1.20.0 ; Media: GtkImage gif player, VLC 3.0.12 Vetinari
```

Does the problem still happen if you remove your config file?

Yes.

**Comment by Cimbali** [comment] 2021-04-10 07:36
Duplicate of #186 and #159. The bugfix will be in the next release, but you can use the current master if you want it immediately.

**Closed by Cimbali** 2021-04-10 07:36 UTC

**Comment by sedrubal** [comment] 2021-04-10 12:49
Thanks!
