### ISSUE TITLE
fedora copr first time install: missing dependency

### ISSUE THREAD

**Issue by ilippert** [Cimbali/pympress#163] opened 2020-07-15 22:47 UTC
### Environment
- fedora 32
- ?
### Pympress
- version 153
- Installation method: copr

### Problem
software does not run - missing `python-vlc`

```
pympress 
Traceback (most recent call last):
  File "/usr/bin/pympress", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-vlc' distribution was not found and is required by pympress
```

**Comment by Cimbali** [comment] 2020-07-16 13:43
Duplicate of #155

**Closed by Cimbali** 2020-07-16 13:43 UTC
