### ISSUE TITLE
Legends in embedded eps/pdf graphics vanish 

### ISSUE THREAD

**Issue by Bonnevie** [Cimbali/pympress#77] opened 2018-09-10 11:16 UTC
# Environment
- Operating system and version
Ubuntu 16.04 LTS
- Python version
3.5

# Pympress
- version
1.2
- Installation method: source, pip, or binary installer?
pip

# Expected behaviour 
What are you trying to achieve? What's the expected outcome?
I am trying to add vector graphics with legends to a Beamer slideshow and displaying it all with pympress. Figures are eps, but converted by beamer/latex to pdf prior to compilation. 

# Steps to reproduce 
Including eps with legend in Beamer, then running pympress. 

# Problem
What's happening instead of what you are expecting?
The legend is missing all text - the legend box and markers are still present, only the explanatory text is gone. The vector graphics issue seems to be key as images using png keep their full legend. Note that the legend is fine in the beamer pdf itself, it is pympress that fails to display it properly.

What is reported in pympress.log?
It is located in the temporary folder, thus one of the following locations:
> /tmp/pympress.log
> /var/tmp/pympress.log
> /usr/tmp/pympress.log
> C:\Users\<username>\AppData\Local\Temp\pympress.log
> C:\TEMP\pympress.log
> C:\TMP\pympress.log

Seems unrelated:
```
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "/home/rabo/.local/lib/python3.5/site-packages/pympress/media_overlay.py", line 548, in <module>
    VLCVideo._instance = vlc.Instance(vlc_opts)
  File "/home/rabo/.local/lib/python3.5/site-packages/vlc.py", line 1731, in __new__
    return libvlc_new(len(args), args)
  File "/home/rabo/.local/lib/python3.5/site-packages/vlc.py", line 4406, in libvlc_new
    ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))
  File "/home/rabo/.local/lib/python3.5/site-packages/vlc.py", line 276, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'

```

**Comment by Cimbali** [comment] 2018-09-10 12:40
Hi @Bonnevie, thanks for reporting this bug. How did you make the eps Figure? Can you provide a pdf with an example, or even better a simple latex code and an eps figure?

I have trouble reproducing myself because I never use eps figures. I tried, and eps files made from svgs with insckape worked fine, while another made with gnuplot seemed to already be stripped of any legends after passing it to eps2pdf. Can you check that your `<image>-eps-converted-to.pdf` generated from the `<image>.eps` has the legends?

(The error is indeed related.)

**Comment by molguin92** [comment] 2018-11-12 04:41
I have what seems to be the same problem, but with embedded PDF generated with MatplotLib on Python 3.7. They look fine in every other PDF viewer I've tried.

I've included a MWE. Note that the text is also missing when you open the raw plot PDF in Pympress, not only when embedded in a pdflatex generated PDF.

LaTeX source:
```latex
\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage{graphics}
\usepackage{xcolor}
\begin{document}
    \begin{frame}{PDF plot}
        \begin{figure}
            \centering
            \includegraphics[width=\linewidth]{./box_taskstep.pdf}
            \caption{Embedded PDF plot from MatplotLib}
        \end{figure}
    \end{frame}
\end{document}
```
[plot.pdf](https://github.com/Cimbali/pympress/files/2570568/plot.pdf)
[beamer.pdf](https://github.com/Cimbali/pympress/files/2570562/bug.pdf)

**Comment by Cimbali** [comment] 2018-11-12 09:59
OK, well I see the text on the figure with opening just the plot pdf, opening your MWE pdf, and recompiling myself. I suppose the difference has to be the Poppler library or one of the drawing libraries, and not the way the pdf is generated.

Can you include the versions of all the required libraries? On Ubuntu it would be something like:

    dpkg -l python3 libgtk-3-0 libpoppler-glib8 libcairo2 python3-gi python3-cairo python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18

On an rpm-based distribution you can do something like:

    rpm -q python3 python3-pip libgtk-3-0 libpoppler-glib8 libcairo2 python3-gobject python3-gobject-Gdk python3-cairo python3-gobject-cairo typelib-1_0-GdkPixbuf-2_0 typelib-1_0-Gtk-3_0 typelib-1_0-Poppler-0_18

Can you also add which pdf viewer(s) you used and their version? okular, evince, foxit, mupdf, or another one?

**Comment by molguin92** [comment] 2018-11-12 22:01
Output of `dpkg -l python3 libgtk-3-0 libpoppler-glib8 libcairo2 python3-gi python3-cairo python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18`:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  gir1.2-gtk-3.0:amd64    3.22.30-1ubuntu1 amd64            GTK+ graphical user interface library -- gir binding
ii  gir1.2-poppler-0.18:amd 0.62.0-2ubuntu2. amd64            GObject introspection data for poppler-glib
ii  libcairo2:amd64         1.15.10-2        amd64            Cairo 2D vector graphics library
ii  libgtk-3-0:amd64        3.22.30-1ubuntu1 amd64            GTK+ graphical user interface library
ii  libpoppler-glib8:amd64  0.62.0-2ubuntu2. amd64            PDF rendering library (GLib-based shared library)
ii  python3                 3.6.5-3ubuntu1   amd64            interactive high-level object-oriented language (def
ii  python3-cairo:amd64     1.16.2-1         amd64            Python3 bindings for the Cairo vector graphics libra
ii  python3-gi              3.26.1-2         amd64            Python 3 bindings for gobject-introspection librarie
ii  python3-gi-cairo        3.26.1-2         amd64            Python 3 Cairo bindings for the GObject library
```

PDF viewers tried: 
- Evince 3.28.4-0ubuntu1
- [pdfpc](https://github.com/pdfpc/pdfpc) 4.1-2

**Comment by molguin92** [comment] 2018-11-12 22:11
I tried your re-encoded PDF plot, and lo-and-behold it works (although the data points in the plot are duplicated for some reason, but I guess that's a LibreOffice problem).

Here's a side-by-side MWE:

```latex
% !TeX root = ./bug.tex
\documentclass{beamer}
\usepackage[backend=biber]{biblatex}
\usepackage[utf8]{inputenc}
\usepackage{graphics}
\usepackage{xcolor}
\begin{document}
\begin{frame}{PDF plot}
    \begin{columns}
        \begin{column}{.5\linewidth}
            \begin{figure}
                \centering
                \includegraphics[width=.8\linewidth]{./plot.pdf}
                \caption{Embedded PDF plot from MatplotLib}
            \end{figure}
        \end{column}%
        \begin{column}{.5\linewidth}
            \begin{figure}
                \centering
                \includegraphics[width=.8\linewidth]{./plot_reencoded.pdf}
                \caption{Re-encoded PDF with LibreOffice}
            \end{figure}
        \end{column}
    \end{columns}
\end{frame}
\end{document}
```

With regards to using MatplotLibs LaTeX text rendering, that's an acceptable work-around for me at the moment, although I've had some issues with it in the past (unrelated to Pympress, so no worries there).

Thanks for the prompt responses!

[plot_reencoded.pdf](https://github.com/Cimbali/pympress/files/2573827/plot_reencoded.pdf)
[plot.pdf](https://github.com/Cimbali/pympress/files/2573828/plot.pdf)
[bug.pdf](https://github.com/Cimbali/pympress/files/2573829/bug.pdf)

**Comment by Cimbali** [comment] 2018-11-12 22:49
Well you seem to have libpoppler 0.62 and I have 0.68. The 0.64 and 0.65 [release notes of Poppler](https://poppler.freedesktop.org/releases.html) mention Type3 font support (though the context doesn't quite fit) and here's what pdffonts has to say about both files:

    $ pdffonts plot.pdf
    name                                 type              encoding         emb sub uni object ID
    ------------------------------------ ----------------- ---------------- --- --- --- ---------
    DejaVuSans                           Type 3            Custom           yes no  no      14  0
    
    $ pdffonts plot_reencoded.pdf
    name                                 type              encoding         emb sub uni object ID
    ------------------------------------ ----------------- ---------------- --- --- --- ---------
    BAAAAA+DejaVuSansMono                TrueType          WinAnsi          yes yes yes     30  0
    CAAAAA+DejaVuSans                    TrueType          WinAnsi          yes yes yes     25  0

Can you generate the file from matplotlib with truetype fonts (by [setting the rc param `pdf.fonttype` to 42](http://phyletica.org/matplotlib-fonts/)), to see if that fixes it? If it does, updating poppler should fix the bug.

**Comment by Cimbali** [comment] 2018-11-12 23:01
Also to isolate this is poppler/cairo and not python/gtk, can you also try converting the buggy plot file to png and see if text is missing? Try `pdftocairo -png plot.pdf`

**Comment by Cimbali** [comment] 2018-11-30 13:38
Closing until some evidence that this is not a bug of the Poppler dependence.

**Closed by Cimbali** 2018-11-30 13:38 UTC
Labels: more info needed

**Comment by ashwinvis** [comment] 2019-09-21 20:29
I had a similar problem with some packages, in particular
```tex
\usepackage{MnSymbol,wasysym}
```
which caused some of the equations to be partially visible. There were Type 3 fonts according to `pdffonts` command. Now that I removed these packages, the whole pdf is embedded with Type 1 fonts. No issues anymore.
