### ISSUE TITLE
Shortcut f does not set content window fullscreen

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#149] opened 2020-03-13 14:03 UTC
# Environment
- Windows 7/10

# Pympress
- 1.5.2
- binary installer

# Expected behaviour 
Shortcut f sets content fullscreen

# Steps to reproduce
Start presentation and press key f (several times)

# Problem
The content window goes not to fullscreen and the entry in the menu presentation the checkbox fullscreen is not set. If I select the checkbox in the menu than all works as expected. It seams that the shortcut f is not working properly.

**Comment by Cimbali** [comment] 2020-03-13 14:20
Can you share your configuration file and log file? The correct paths are specified in the Help > About dialog.

**Comment by eddrog** [comment] 2020-03-13 15:11
[pympress.conf.txt](https://github.com/Cimbali/pympress/files/4330212/pympress.conf.txt)
[pympress.log](https://github.com/Cimbali/pympress/files/4330218/pympress.log)

**Comment by Cimbali** [comment] 2020-03-24 01:54
Does any of the other shortcuts work? F5 or F11 for example?

**Comment by eddrog** [comment] 2020-03-24 17:08
Same behaviour for all keys

**Comment by Cimbali** [comment] 2020-04-10 18:38
Had a look, but nothing seems out of the ordinary in your configuration and nothing at all shows up in the log.

Can you try with debug logging? For example starting with `pympress --log=debug`

**Comment by eddrog** [comment] 2020-04-11 13:48
ERROR:pympress.extras:Videounterstützung auf Basis von GStreamer ist deaktiviert.
Traceback (most recent call last):
  File "C:\projects\pympress/pympress/extras.py", line 420, in _setup_backends
  File "C:\projects\pympress/pympress/media_overlays/gst_backend.py", line 33, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
ValueError: Namespace Gst not available
ERROR:pympress.extras:Videounterstützung auf Basis von VLC ist deaktiviert.
Traceback (most recent call last):
  File "C:\projects\pympress/pympress/extras.py", line 438, in _setup_backends
  File "C:\projects\pympress/pympress/media_overlays/vlc_backend.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:/msys64/mingw64/lib/python3.8/site-packages/vlc.py", line 207, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/vlc.py", line 163, in find_lib
  File "C:/msys64/mingw64/lib/python3.8/ctypes/__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'libvlc.dll'. Try using the full path with constructor syntax.
INFO:__main__:Pympress: 1.5.2 ; Python: 3.8.1 ; OS: Windows 10 10.0.18362 ; Gtk 3.24.13 ; GLib 2.62.1 ; Poppler 0.84.0 cairo ; Cairo 1.16.0 , pycairo 1.19.0 ; Media: Gif-Wiedergabe mit GtkImage
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\projects\pympress/pympress/ui.py", line 490, in save_and_quit
AttributeError: 'NoneType' object has no attribute 'get_state'

**Comment by eddrog** [comment] 2020-04-11 13:49
You can not reproduce this behaviour?

**Comment by Cimbali** [comment] 2020-04-11 14:06
No I haven’t been able to reproduce the behaviour. However the uncaught exception in your log file _might_ be interesting.

The code is `self.c_win.get_window().get_state()` and the returned window seems to be `None` somehow. That window attribute is obviously also used to set the window fullscreen.

**Comment by raphaelquast** [comment] 2020-10-21 15:31
i can reproduce this on my pc (windows 10)!

with a fresh-install of pympress all shortcuts work perfectly except for the fullscreen-ones

- if i am in fullscreen mode, they work properly
- if i am no longer in fullscreen they do nothing (e.g. they don't toggle they just deactivate)

**Comment by Cimbali** [comment] 2020-10-22 17:10
Thanks @raphaelquast, can you also show your logs ? Maybe we can get a better idea of what’s happening

**Comment by raphaelquast** [comment] 2020-10-22 17:42
here you go:   (i guess it still contains some previous errors as well from testing the annotate-feature ... but maybe you find something useful in there 😄 )
[pympress.log](https://github.com/Cimbali/pympress/files/5424636/pympress.log)

if you want i can generate a plain new one as well?

**Comment by Cimbali** [comment] 2021-04-04 15:04
This will need some testing again with the current master (or next release), as the whole system for shortcuts has changed.

**Comment by eddrog** [comment] 2021-04-06 13:37
I have tested it on a Win10 Desktop -> works. Tonight I will test it on my Win10 tablet and I'll let you know if it is fixed. But the Big keys next/prev and laserpointer switch are deactivated.

**Comment by eddrog** [comment] 2021-04-07 06:42
Also testet on Win10 Tablet -> fixed. But the keys are still disabled next/prev and laserpointer (version beta5).

**Comment by Cimbali** [comment] 2021-04-07 08:50
Thanks @eddrog, I'm closing this issue and I'll fix the buttons before the release.

**Closed by Cimbali** 2021-04-07 08:50 UTC
Labels: more info needed
