### ISSUE TITLE
Videos play in a new window instead of playuing inside the PDF

### ISSUE THREAD

**Issue by cpitclaudel** [Cimbali/pympress#184] opened 2021-03-02 07:04 UTC
### Environment

- Linux mint 20.1
- Python 3.8.6

### Pympress
- 1.5.3
- pip3

Media support uses GtkImage gif player, VLC 3.0.9.2 Vetinari.
Python version 3.8.6 (default, Oct  9 2020, 11:59:16) 
[GCC 9.3.0]

### Expected behaviour

I would like to play a video embedded in a PDF.  

### Steps to reproduce

I used the example from https://github.com/Cimbali/pympress/issues/60#issuecomment-374010933

### Problem

Videos open in a separate VLC window.  The console contains this:

```
[00007f4bbc006a90] main filter error: Failed to create video converter
[00007f4bc4008350] main filter error: Failed to create video converter
[00007f4bd40a1a30] vdpau_avcodec generic error: Xlib is required for VDPAU
[00007f4bd00f27e0] vdpau_avcodec generic error: Xlib is required for VDPAU
[00007f4bd4095440] xcb_window window error: X server failure
[00007f4bd0089400] xcb_window window error: X server failure
```

What is reported in pympress.log?

```
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/clement/.local/lib/python3.8/site-packages/pympress/util.py", line 81, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/clement/.local/lib/python3.8/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
ERROR:pympress.extras:Video support using GStreamer is disabled.
INFO:pympress.extras:Caused by ValueError: Namespace GstPlayer not available
INFO:pympress.__main__:Pympress: 1.5.3 ; Python: 3.8.6 ; OS: Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 ; Gtk 3.24.20 ; GLib 2.64.2 ; Poppler 0.86.1 cairo ; Cairo 1.16.0 , pycairo 1.16.2 ; Media: GtkImage gif player, VLC 3.0.9.2 Vetinari
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
WARNING:pympress.media_overlays.base:Not showing media with (some) negative margin(s): LTRB = (0.08020450066834789, 0.34242593504479546, 0.4979205423953036, -0.3424259350447954)
WARNING:pympress.media_overlays.base:Not showing media with (some) negative margin(s): LTRB = (0.08020450066834789, 0.34242593504479546, 0.4979205423953036, -0.3424259350447954)
```

Does the problem still happen if you remove your config file? Yes

**Comment by Cimbali** [comment] 2021-03-02 07:34
The bottom margin seems negative, from the error log. Can you try specifying a height or reducing the width until that error message disappears?

That is not how that issue should be handled though in the current code

**Comment by Cimbali** [comment] 2021-03-02 08:09
This seems to be a duplicate of #160, as you still have the error message from before that fix.

**Closed by Cimbali** 2021-03-02 08:09 UTC

**Comment by cpitclaudel** [comment] 2021-03-02 14:02
Good catch, thanks a lot!
