### ISSUE TITLE
Pre-rendering not working; 100% CPU usage

### ISSUE THREAD

**Issue by fefrei** [Cimbali/pympress#18] opened 2017-03-15 09:30 UTC
I'm running pympress 1.0 on Windows, and pre-rendering doesn't seem to be working:

- Pympress is constantly using one CPU core.
- If I simply wait, RAM usage doesn't go up.
- If I click through the slides, some complex slides take a fraction of a second to render. RAM usage goes up while I do this.
- After having clicked through all slides once, RAM usage is high (1.56 GB for a >100 slides presentation), and clicking through the slides is smooth.

To me, it looks like the prerenderer gets stuck, burning CPU without progressing.

(I'd be happy to privately send you the PDF file I use, if this helps you debugging this.)

**Comment by Cimbali** [comment] 2017-03-16 14:40
Interesting, I'll take a look as soon as I can. Did you install with the binary installer? If so, the 32 or 64 bit version? If not, can you tell me your version of python?

**Comment by fefrei** [comment] 2017-03-16 14:42
I did use the binary installer in its 64 bit version. (I'm running Windows 10.)

**Comment by fefrei** [comment] 2017-03-18 18:05
I experimented some more, and reinstalled `pympress` (version `1.0`).

It does make a difference whether `pympress` is started with a PDF file passed on the command line or whether it is picked in the UI!

Here are performance graphs for about 2 minutes after starting `pympress` with a PDF file:

![image](https://cloud.githubusercontent.com/assets/3078885/24074644/19e1ced4-0c0d-11e7-9e95-eaf00117470c.png)

For comparison, here is the result of starting `pympress` without a file, and selecting the (same) file after launch:

![image](https://cloud.githubusercontent.com/assets/3078885/24074679/a65bac86-0c0d-11e7-8009-ea24bceb82fe.png)

So here, CPU usage is still weirdly high (10 seconds / one core of CPU time for one slide), but it's no longer infinite 🙂

**Comment by Cimbali** [comment] 2017-03-23 20:14
Alright, it was hard to reproduce since it only happened on the built binary versions for some unknown reason, but I think I've fixed it. Check it out [here](https://github.com/Cimbali/pympress/releases/tag/v1.0.2) and I'll close the issue if you confirm it's all good.

**Comment by fefrei** [comment] 2017-03-24 07:23
I'm sorry, but it looks like the behavior didn't change...

What I did notice: The CPU usage drops as soon as `pympres` loses focus.

**Comment by fefrei** [comment] 2017-03-24 07:33
Even more weirdly: The high CPU usage occurs when switching to the next slide with the keyboard. It subsides as soon as the mouse is moved within any of `pympress`'s windows.

**Comment by Cimbali** [comment] 2017-03-24 12:09
Sounds like something is uninitialized for a while causing some trouble. Can't reproduce for now, with Python3.4 on Windows 7. I have a Windows 10 I can get my hands on, see if that helps.

**Comment by Cimbali** [comment] 2017-03-30 22:10
Alright I haven't been able to reproduce this on Windows 10. I'm pretty busy right now but I'll try to devise some way to identify what's going wrong soon. I'll probably need you to run a modified version of pympress with a bunch of debug logging enabled, basically.

**Comment by fefrei** [comment] 2017-03-31 07:35
No problem – I'd guess that this is a race condition somewhere, making it hard to debug.
I'd be happy to help! (If it would help you, I could also try to provide process dumps during the high-CPU phases.)

**Comment by Cimbali** [comment] 2017-05-30 22:13
Alright, it took me some time to figure out how to log from a built binary (since you can't just print).

Here's a (zipped) binary installer, that corresponds to the current tip of [the debug_win10_prerendering branch](https://github.com/Cimbali/pympress/tree/debug_win10_prerendering), 8236527:

[pympress-1.0.3-amd64.zip](https://github.com/Cimbali/pympress/files/1039811/pympress-1.0.3-amd64.zip)

If you run it with `--log=debug` you should see a file called `pympress.log` appear, with some verbose info on what the prerendering is doing or attempting to do.

**Comment by fefrei** [comment] 2017-05-31 10:07
The bug is still happening, and I think I did a good capture. Here's what I did:

- started `pympress` with the arguments `--log=debug talk-annotated.pdf`
- on a third monitor, set up Process Hacker to monitor CPU usage
- pressed <kbd>Page ↓</kbd> to advance a slide
- observed high CPU for about 20 seconds
- moved the mouse
- observed an immediate drop in CPU usage
- closed `pympress` be pressing <kbd>Q</kbd>

Here's the CPU usage graph during this test:

![image](https://cloud.githubusercontent.com/assets/3078885/26626785/adee3dfe-45f8-11e7-8f64-e7887cb9a17e.png)

And here is the log file [pympress.log](https://github.com/Cimbali/pympress/files/1040992/pympress.log.txt), renamed to `.txt` to appease out GitHub overlords.

I'll send you an email with the PDF file to your Git email address in a second.

**Comment by Cimbali** [comment] 2017-05-31 10:37
Alright, I received it and compared with running here on windows 7 and everything looks the same. No extra work in pre-rendering, you render 5 slides (x3 different-sized widgets) at the beginning and one when you change the page. That seems to fit with the memory and I/O statistics as well. So I think it's not the pre-rendering causing the problems.

I guess I'll have to look at what happens on page change and anything related to mouse event next.

**Comment by Cimbali** [comment] 2018-02-12 23:33
Hei @fefrei I read that drap&drop in Gtk might cause high CPU usage. To check if that is the case (and if you can still reproduce the bug), you could check out the [debug/win10_prerendering](https://github.com/Cimbali/pympress/tree/debug/win10_prerendering) branch where I deactivated the drag & drop functionality for testing purposes.

**Comment by fefrei** [comment] 2018-02-13 15:49
Hi @Cimbali! I can still reproduce the CPU load in Pympress `1.1.1` (from the official MSI package). I'd be happy to test the debug version if you can build an installer for it again, I'm having trouble running it from source (which is most likely my fault).

**Comment by Cimbali** [comment] 2019-02-21 17:26
If this is still reproducible, it would be interesting to look at the output of running `GDK_DEBUG=draw,cursor pympress` so we can see the events and identify which cause the high CPU usage.

**Comment by fefrei** [comment] 2019-02-22 09:16
Hm, where is that output supposed to appear? The command terminates before the window opens, and I don't see a log file anywhere. (I installed the most recent version via the MSI installer.)

**Closed** 2022-11-26 20:06 UTC
Labels: bug
