### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by cpbl** [Cimbali/pympress#158] opened 2020-05-29 02:38 UTC
The link/image for "A screenshot with Pympress’ 2 screens" in `README.md` is broken for me; I get

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied</Message>
> <RequestId>D8512442F7B380E0</RequestId>
> <HostId>JMQiHTlnTLYnm0DjqDDNUKZBZxoX9AuEOlSL6sZHoUGG9tu17hXKcvDDuMNG8bZW1F639wnVroQ=</HostId>
> </Error>

rather than seeing an image

**Comment by Cimbali** [comment] 2020-05-29 08:46
Duplicate of #153

**Closed by Cimbali** 2020-05-29 08:46 UTC
